config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'

  devise_for :users

  devise_scope :user do
    root 'users#index'
    resources :users, only: [:index, :show] do
      resources :posts, only: [:index, :show, :new, :create, :destroy] do
        resources :likes, only: [:create, :destroy]
        resources :comments, only: [:new, :create, :destroy]
      end
    end  
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show], defaults: {format: :json} do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :read, :all
    can :manage, Post, author: user
    can :manage, Comment, author: user
    can :manage, :all if user.is? :admin
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_post_comments_counter

  private

  def update_post_comments_counter
    post.update_comments_counter
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_post_likes_counter

  private

  def update_post_likes_counter
    post.update_likes_counter
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  after_create :update_author_posts_count

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  def update_comments_counter
    update(comments_counter: comments.count)
  end

  def update_likes_counter
    update(likes_counter: likes.count)
  end

  private

  def update_author_posts_count
    author.update(posts_count: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true
  validates :password, presence: true
  validates :posts_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ActionController::API
  def index
    comments = Comment.where(author_id: params[:user_id])
    render json: comments, status: :ok
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.author = @user

    if @comment.save
      render json: @comment, status: :created
    else
      render json: { error: @comment.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ActionController::API
  before_action :find_user

  def index
    @posts = @user.posts
    render json: @posts
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio role])
  end

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :bio, :role, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    post = Post.find(params[:post_id])
    comment = current_user.comments.new(comments_params)
    comment.post = post
    if comment.save
      redirect_to user_post_url(id: params[:post_id])
    else
      render user_post_path(id: current_user.id)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    @post = Post.find(@comment.post_id)
    redirect_to user_path(current_user.id), notice: 'Deleted.'
  end

  private

  def comments_params
    params.require(:add_comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    user_like = current_user.likes.new(post:)
    if user_like.save
      flash[:success] = 'You liked this post'
      redirect_to user_post_url(id: params[:post_id])
    else
      flash.now[:error] = 'Error: Post could not be created'
      render user_post_path(id: current_user.id)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
  end

  def show
    @post = User.find(params[:user_id]).posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.comments_counter = 0
    @post.likes_counter = 0

    if @post.save
      redirect_to user_post_path(current_user, @post)
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    Comment.where(post_id: @post.id).destroy_all
    Like.where(post_id: @post.id).destroy_all
    @post.destroy
    flash[:success] = 'Post Has been deleted'
    redirect_to user_path(@post.author), notice: 'Deleted!'
  end

  private

  def post_params
    params.require(:add_post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="form-card">
<%= form_with model: @comment, url: user_post_comments_path(post_id: @post.id), method: :post, local: true, scope: :add_comment do |form| %>
  <div>
    <%= form.label :text %><br>
    <%= form.text_area :text, size: "90x5" %>
  </div>

  <%= form.submit %>
<% end %>

<% flash.each do |name, msg| -%>
  <%= content_tag :span, msg, class: name %>
<% end -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<%= link_to(user_post_path(@user, post)) do%>
  <div class="comment-card border-deco all-user-post">
    <div class="comment-info">
      <h3>Post <%= post_counter + 1 %></h3>
      <p><%= post.text %></p>
    </div>
    <div class="counter-card d-flex">
      <span>Total Comments: <%= post.comments_counter%></span>
      <span>Total Likes: <%= post.likes_counter%></span>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="bio-card">
  <%= render @user %>
</div>
<div class="bio-card">
  <% @user.posts.each_with_index do |post, index|%>
    <div class="comment-bio-card">
      <%= render partial: "post", locals: { post_counter: index, post: post } %>
    </div>
    <div class="comments-card border-deco">
      <% post.recent_comments.includes(:author).each do |comment|%>
        <p class="d-flex"><span><%= comment.author.name %>:</span><span><%= comment.text %></span></p>
      <% end %>
    </div>
  <% end %>
</div>
<div class="post-btn-card d-flex">
    <button class="posts-btn border-deco">Pagination</button>
</div>

app/views/posts/new.html.erb
<div class="form-card form-card-margin">
  <%= form_with model: @post, url: user_posts_path(user_id: current_user.id), method: :post, local: true, scope: :add_post do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :text %><br>
      <%= form.text_area :text, size: "80x6" %>
    </div>

    <%= form.submit %>
  <% end %>

  <% flash.each do |name, msg| -%>
    <%= content_tag :span, msg, class: name %>
  <% end -%>
</div>

app/views/posts/show.html.erb
<div class="post-details-card">
  <div class="single-post-info border-deco">
    <div class="title-details d-flex">
    <% if can? :destroy, @post %>
        <%= button_to "Delete post", user_post_path(@post.author, @post), method: :delete %>
      <%end%>
      <p><%= @post.title %> by <%= @post.author.name%></p>
      <div>
        <span>All Comments: <%= @post.comments_counter%></span>
        <span>All Likes: <%= @post.likes_counter%></span>
      </div>
    </div>
    <div>
      <%= @post.text %>
      <%= form_with url: user_post_likes_path(@post.author, @post), method: :post, local: true do |form| %>
        <%= form.button type: :submit, class: 'link-button' do %>
          <span class="heart-icon">&#x2665;</span>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="comments-card border-deco">
    <% @post.recent_comments.includes(:author).each do |comment|%>
      <p class="d-flex"><span><%= comment.author.name %>:</span><span><%= comment.text %><% if can? :delete, comment %>
            <%= button_to "Delete comment", user_post_comment_path(comment.author, comment.post, comment), method: :delete %>
          <%end%></span></p>
    <% end %>
  </div>
  <%= render template: 'comments/new', post_id: @post.id %>
</div>

app/views/users/_user.html.erb
<%= link_to(user) do %>
<article class="container d-flex">
  <div class="img-container border-deco">
    <img src="<%= user.photo %>" alt="<%= user.name %>' s Photo" class="photo">
  </div>
  <div class="user-info d-flex border-deco">
    <h1><%= user.name %></h1>
    <p class="posts">Number of Posts: <%= user.posts_count %></p>
  </div>
</article>
<% end %>

app/views/users/index.html.erb
  <div>
    <%= render @users %>
  </div>

app/views/users/show.html.erb
<section>
  <div>
    <%= render @user %>
  </div>
  <div class="user-card">
    <div class="user-info border-deco">
      <h3>Bio</h3>
      <p>
        <%= @user.bio%>
      </p>
    </div>
    <div>
      <%= render partial: "posts/post", collection: @user.posts %>
    </div>
  </div>
   <%= render template: 'posts/new', collection: @user.posts %>
  <div class="post-btn d-flex">
   <button class="posts-btn border-deco">
      <%= link_to 'See All Posts', user_posts_path(@user.id) %>
    </button>
  </div>
</section>